<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HomeInsurance_MVC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Items\Create.cshtml" />
    <Content Remove="Views\Items\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Views\Items\Create.cshtml" />
    <Compile Include="Views\Items\Index.cshtml" />
  </ItemGroup>

</Project>
